apiVersion: v1
kind: Pod
metadata:
  name: hN-t-add-sysadmin
spec:
  hostNetwork: true
  containers:
  - name: my-container
    image: rockylinux
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10; done"]
    securityContext:
     capabilities:
      drop:
      - ALL
      add: ["SYS_ADMIN"]
