apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  hostNetwork: true
  containers:
  - name: my-container
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      drop:
       - ALL
      add:
       - SYS_ADMIN
