apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      hostNetwork: false
      containers:
      - name: busybox
        image: busybox
