apiVersion: v1
kind: Pod
metadata:
  name: hn-f-addded-sys-admin
spec:
  hostNetwork: false
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
