apiVersion: v1
kind: Pod
metadata:
  name: hostnetwork-false-add-capabilities
spec:
  hostNetwork: false
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
