apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
hostNetwork: false
  containers:
  - name: my-container
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
