apiVersion: v1
kind: Pod
metadata:
  name: hN-t-drop-all-add-net-admin
spec:
  hostNetwork: true
  containers:
  - name: my-container
    image: rokylinux:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    securityContext:
     capabilities:
      drop:
      - ALL
      add: ["NET_ADMIN"]
