apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  hostNetwork: false
  containers:
  - name: pod1
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      drop:
       - ALL
      add:
       - CHOWN
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  hostNetwork: false
  containers:
  - name: pod2
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  hostNetwork: false
  containers:
  - name: pod3
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      drop:
       - ALL
      add:
       - CHOWN
    
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
spec:
  hostNetwork: true
  containers:
  - name: pod4
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      drop:
       - ALL
      add:
       - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  hostNetwork: true
  containers:
  - name: pod5
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      drop:
       - ALL
      add:
       - SYS_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  hostNetwork: true
  containers:
  - name: my-container
    image: nicolaka/netshoot
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      drop:
      - ALL
      add: ["NET_ADMIN"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod6
spec:
  hostNetwork: true
  containers:
  - name: pod6
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 360000; done"]
    securityContext:
     capabilities:
      add:
       - CHOWN
      drop:
       - ALL

    
